<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fbit_berecordlist"
 *
 * Auto generated by Extension Builder 2017-07-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BE Record Lists',
    'description' => 'Creates modules to view individual record lists.',
    'category' => 'module',
    'author' => 'Grigori Prokhorov',
    'author_email' => 'hello@feinberg.it',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
